server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # 헬스체크 엔드포인트
    location = /healthz {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    # 정적 파일 캐싱 예시, 빌드 때 파일 해싱이 변경되어 영구 캐싱해도 문제 없음
    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico)$ {
        try_files $uri =404;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    # SPA 라우팅: 파일 없으면 index.html 반환
    location / {
        try_files $uri $uri/ /index.html;
    }
}